version: "3.8"

services:
  # Node.js server
  node_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5500  # Set the environment to "development" if not explicitly set
    ports:
      - 5000:5500  # Map host port to container port
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - redis_stack
    # deploy:
    #   replicas: 2

  # Redis cache
  redis_stack:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379  # Map host port to container port
      - 8001:8001
    environment:
      - REDIS_ARGS= --appendonly yes
    volumes:
      - redis_data:/data


volumes:
  redis_data:
